language: ruby

rvm:
  - 2.1.*
  - 2.2.*
  - 2.3.*
  - 2.4.*

gemfile:
  - Gemfile
  - Gemfile.fluentd.0.12

matrix:
  exclude:
    - rvm: 2.0.*
      gemfile: Gemfile

before_install: gem update bundler

script: 'bundle exec rake test'
